# Generated by Django 4.0.4 on 2022-06-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataDeOcupação', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('forma_garantia', models.CharField(max_length=100)),
                ('fiador', models.CharField(max_length=100)),
            ],
        ),
    ]
