# Generated by Django 4.0.4 on 2022-06-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dadosCliente', models.CharField(max_length=100)),
                ('dadosCorretor', models.CharField(max_length=100)),
                ('descriçãoImovel', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('documentação', models.CharField(max_length=100)),
                ('clausulaPenal', models.CharField(max_length=100)),
            ],
        ),
    ]
